services:
  client-service:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    networks:
      - my_network
  server-service:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - .env
    networks:
      - my_network
  python-service:
    build:
      context: ./python
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    cpus: "4.0"
    cpuset: "0-3"
    mem_reservation: "6g"
    mem_limit: "8g"
    networks:
      - my_network
    command: ["python", "app.py"]
networks:
  my_network: